name: Slither

on: [push, pull_request, pull_request_target]

jobs:
  slither:
    name: Slither Analysis
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: ['12.x']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: Install Project Dependencies
        run: npm ci

      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Cache pip
        uses: actions/cache@v2
        with: 
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install Slither
        run: |
          python -m pip install --upgrade pip
          pip3 install slither-analyzer
        
      - name: Run Slither and Generate SARIF file
        run: npm run slither -- --sarif slither.sarif || true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "slither.sarif"